"""empty message

Revision ID: 8b1e8d91241d
Revises: afc2aee2f187
Create Date: 2025-05-25 18:07:03.000358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1e8d91241d'
down_revision: Union[str, None] = 'afc2aee2f187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict', sa.Column('price', sa.Integer(), nullable=True))
    op.alter_column('predict', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predict', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('predict', 'price')
    # ### end Alembic commands ###
